spring:
  jackson:
    defaultPropertyInclusion: "non_null"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    showSql: 'true'
    hibernate:
#      ddl-auto: 'create-drop'
      ddl-auto: update
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        order_by:
          default_null_ordering: last

  kafka:
    bootstrap-servers: localhost:9092
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
          ssl:
            enable: true
        transport:
          protocol: smtp
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # lub 'never' jeśli nie chcesz, aby Spring zarządzał schematem
    properties:
      org.quartz.scheduler.instanceName: MyScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.isClustered: false
      org.quartz.threadPool.threadCount: 5
      org.quartz.dataSource.quartzDS.driver: org.postgresql.Driver
      org.quartz.dataSource.quartzDS.URL: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
      org.quartz.dataSource.quartzDS.user: ${POSTGRES_USER}
      org.quartz.dataSource.quartzDS.password: ${POSTGRES_PASSWORD}
      org.quartz.dataSource.quartzDS.maxConnections: 30
      org.quartz.jobStore.dataSource: quartzDS

application:
  security:
    access-jwt:
      secret-key: 4158465a2f6a272c253b4468423246663f3c4a7951673a544c452e2c4d36465c
      expiration: 600000 # 10 minutes
#      expiration: 3600000 // 1 hour
    refresh-jwt:
      secret-key: 294C4D868F5CC153E538D5DD921B1612263C3D700EF1662E6C89903DE0FF3F9F
      expiration: 2592000000
    verification-jwt:
      secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      expiration: 86400000